import React from "react";
import { View, ScrollView, Alert } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Ionicons } from "@expo/vector-icons";
import { ScreenHeader } from "@/components/ui/ScreenHeader";
import { Card } from "@/components/ui/Card";
import { Text } from "@/components/ui/Text";
import { StatRow } from "@/components/ui/StatCard";
import { Button } from "@/components/ui/Button";
import { colors } from "@/constants/theme";
import { getDatasetRange } from "@/data/mock/eventGenerator";
import { getAllEvents } from "@/data/mock/eventGenerator";
import { formatDate } from "@/utils/format";
import { LEAGUES, BOOKMAKERS } from "@/data/mock/reference";

const range = getDatasetRange();

export default function SettingsScreen() {
  function handleReset() {
    Alert.alert("Reset all data", "This clears every saved strategy and backtest result. This can't be undone.", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Reset",
        style: "destructive",
        onPress: async () => {
          await AsyncStorage.removeItem("edge-terminal:v1");
          Alert.alert("Data reset", "Restart the app to reseed example strategies.");
        },
      },
    ]);
  }

  const totalEvents = getAllEvents().length;

  return (
    <SafeAreaView edges={["top"]} className="flex-1 bg-canvas">
      <ScreenHeader title="Settings" subtitle="Edge Terminal · v1.0.0 prototype" />
      <ScrollView className="px-5" contentContainerStyle={{ paddingBottom: 32 }} showsVerticalScrollIndicator={false}>
        <View className="flex-row items-center gap-3 mb-2">
          <View className="w-11 h-11 rounded-xl bg-edge/15 border border-edge/30 items-center justify-center">
            <Ionicons name="terminal-outline" size={20} color={colors.edge} />
          </View>
          <View>
            <Text className="font-sans-semibold text-[15px]">Edge Terminal</Text>
            <Text className="text-text-tertiary text-xs mt-0.5">Sports backtesting prototype</Text>
          </View>
        </View>

        <Text className="font-sans-semibold text-[14px] mt-6 mb-2">Data source</Text>
        <Card className="px-4">
          <StatRow label="Mode" value="Simulated historical data" />
          <StatRow label="Dataset range" value={`${formatDate(range.from)} – ${formatDate(range.to)}`} />
          <StatRow label="Simulated events" value={totalEvents.toLocaleString()} />
          <StatRow label="Leagues covered" value={String(LEAGUES.length)} />
          <StatRow label="Bookmakers" value={String(BOOKMAKERS.length)} isLast />
        </Card>
        <Text className="text-text-tertiary text-xs mt-2 leading-5 px-1">
          All results, odds, and outcomes are generated by a deterministic mock data engine — no live sports or odds
          API is connected yet. The data layer is structured so a real provider can be swapped in later without
          changing any screens.
        </Text>

        <Text className="font-sans-semibold text-[14px] mt-6 mb-2">Preferences</Text>
        <Card className="px-4">
          <StatRow label="Theme" value="Dark (default)" />
          <StatRow label="Currency" value="USD ($)" isLast />
        </Card>

        <Text className="font-sans-semibold text-[14px] mt-6 mb-2">Account</Text>
        <Card className="px-4">
          <StatRow label="Sign in" value="Not implemented" />
          <StatRow label="Payments" value="Not implemented" isLast />
        </Card>

        <View className="mt-7">
          <Button label="Reset All Data" variant="danger" icon="refresh-outline" fullWidth onPress={handleReset} />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
